[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
offline = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
ffi = false
fs_permissions = []
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[profile.default.fuzz]
runs = 256
seed = "0x54495053"

[fmt]
line_length = 120
ignore = ["lib/**"]
